highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
url: http://drenniks.github.io/
baseurl: "/"
title: Danielle Skinner
name: Danielle Skinner
email: drenniks@gatech.edu
email_full: mailto:drenniks@gatech.edu
website: drenniks.github.io
website_full: https://drenniks.github.io
github: drenniks
twitter: drenniks
google_analytics: UA-85469455-1

# needed for travis-ci build
exclude: [vendor]